name: CI-clip

on:
  schedule:
    - cron: "22 */5 * * *"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Before build
        run:  python src/open_clip/constants.py

