---
# yamllint disable rule:line-length
name: CI 

on:
  push:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04 
    name: tirith 
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1

      - name: Before build
        run: |
          python src/open_clip/constants.py

